services:
  app:
    build: .
    ports:
      - "5173:5173"  # Map the Vite port
    volumes:
      - .:/app  # Mount the current directory to /app in the container
      - /app/node_modules  # Prevent overwriting node_modules in the container
    environment:
      - CHOKIDAR_USEPOLLING=true  # Enable polling for file changes
